name: Update Dependencies

on:
  schedule:
    - cron: '0 0 1 * *' # Monthly on the 1st
  workflow_dispatch: # Manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Update dependencies
      run: |
        npx npm-check-updates -u
        npm install
        npm test
        npm run build
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          Automated dependency updates
          
          - Updated all dependencies to latest versions
          - Tests passing
          - Build successful
        branch: dependency-updates
        delete-branch: true